- name: ping play
  hosts: all
  gather_facts: no
  tasks:
    - name: debug
      debug:
        msg: "{{ ansible_host }} is successfully connected"
    - name: print interfaces
      ios_command:
        commands:
          - sh ip int br
          - sh version
      register: output
    - name: debug output
      debug:
        msg: "{{ output.stdout_lines[0] }} and {{output.stdout_lines[1][0]}}"



