ansible_network_os: cisco.ios.ios
ansible_connection: network_cli
ansible_become: yes
ansible_become_method: enable
ansible_become_password: controller123@
ansible_user: controller
ansible_password: controller123@